version: '3.8'

services:
  frontend:
    build:
        context: ./Frontend
        dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:80"
    restart: unless-stopped